#%RAML 1.0
title: Employee Lookup Process API
version: v2.0
baseUri: http://localhost:8081/api


types:
  employeeMapping: !include dataTypes/EmployeeMapping.raml
  errorResponse: !include dataTypes/ErrorResponse.raml
  successResponse: !include dataTypes/SuccessResponse.raml

/employees:
  post:
    displayName: Create employee mapping
    description: |
      Create the employee mapping
    body: 
      application/json:
        type: employeeMapping
        example: !include examples/post_employees_example.yaml
    responses:
      201:
        body: 
          application/json:
            type: successResponse
            example: |
                {
                  "id": "asdasfsa89f7s87faas87f98as7f98sa7"
                }

        
  /{id}:
    uriParameters:
      id:
        type: string
        example: 20a5ea46-a4ee-4542-93f4-9040a4ec078b
        description: Represents the employee unique id in form of UUID
    get:
      displayName: Get employee mapping by id
      description: Get Employee mapping by ID
      responses:
        200:        
          body:
            application/json:
              type: employeeMapping
              example: !include examples/get_employee_example.yaml
              
        404:
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "Resource not found"
                }